/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PortalWhatsappRouteImport } from './routes/portal.whatsapp'
import { Route as PortalVoiceRouteImport } from './routes/portal.voice'
import { Route as PortalSettingsRouteImport } from './routes/portal.settings'
import { Route as PortalScriptsRouteImport } from './routes/portal.scripts'
import { Route as PortalMeetingsRouteImport } from './routes/portal.meetings'
import { Route as PortalLiveCallsRouteImport } from './routes/portal.live-calls'
import { Route as PortalLeadsRouteImport } from './routes/portal.leads'
import { Route as PortalInboundRouteImport } from './routes/portal.inbound'
import { Route as PortalCostsRouteImport } from './routes/portal.costs'
import { Route as PortalCampaignsRouteImport } from './routes/portal.campaigns'
import { Route as PortalCallsRouteImport } from './routes/portal.calls'
import { Route as PortalCallbacksRouteImport } from './routes/portal.callbacks'
import { Route as PortalBillingRouteImport } from './routes/portal.billing'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout.success'
import { Route as AdminWaTemplatesRouteImport } from './routes/admin.wa-templates'
import { Route as AdminScriptsRouteImport } from './routes/admin.scripts'
import { Route as AdminResetPasswordRouteImport } from './routes/admin.reset-password'
import { Route as AdminProfileRouteImport } from './routes/admin.profile'
import { Route as AdminPlansRouteImport } from './routes/admin.plans'
import { Route as AdminNumbersRouteImport } from './routes/admin.numbers'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminForgotPasswordRouteImport } from './routes/admin.forgot-password'
import { Route as AdminCreditsRouteImport } from './routes/admin.credits'
import { Route as AdminClientsRouteImport } from './routes/admin.clients'
import { Route as AdminBillingRouteImport } from './routes/admin.billing'
import { Route as PortalWhatsappIndexRouteImport } from './routes/portal.whatsapp.index'
import { Route as PortalCampaignsIndexRouteImport } from './routes/portal.campaigns.index'
import { Route as PortalWhatsappTemplatesRouteImport } from './routes/portal.whatsapp.templates'
import { Route as PortalWhatsappMessagesRouteImport } from './routes/portal.whatsapp.messages'
import { Route as PortalWhatsappCampaignsRouteImport } from './routes/portal.whatsapp.campaigns'
import { Route as PortalInboundReceptionistRouteImport } from './routes/portal.inbound.receptionist'
import { Route as PortalInboundNumbersRouteImport } from './routes/portal.inbound.numbers'
import { Route as PortalInboundCallsRouteImport } from './routes/portal.inbound.calls'
import { Route as PortalInboundAnalyticsRouteImport } from './routes/portal.inbound.analytics'
import { Route as PortalCampaignsIdRouteImport } from './routes/portal.campaigns.$id'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PortalWhatsappRoute = PortalWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => PortalRoute,
} as any)
const PortalVoiceRoute = PortalVoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => PortalRoute,
} as any)
const PortalSettingsRoute = PortalSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PortalRoute,
} as any)
const PortalScriptsRoute = PortalScriptsRouteImport.update({
  id: '/scripts',
  path: '/scripts',
  getParentRoute: () => PortalRoute,
} as any)
const PortalMeetingsRoute = PortalMeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => PortalRoute,
} as any)
const PortalLiveCallsRoute = PortalLiveCallsRouteImport.update({
  id: '/live-calls',
  path: '/live-calls',
  getParentRoute: () => PortalRoute,
} as any)
const PortalLeadsRoute = PortalLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => PortalRoute,
} as any)
const PortalInboundRoute = PortalInboundRouteImport.update({
  id: '/inbound',
  path: '/inbound',
  getParentRoute: () => PortalRoute,
} as any)
const PortalCostsRoute = PortalCostsRouteImport.update({
  id: '/costs',
  path: '/costs',
  getParentRoute: () => PortalRoute,
} as any)
const PortalCampaignsRoute = PortalCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => PortalRoute,
} as any)
const PortalCallsRoute = PortalCallsRouteImport.update({
  id: '/calls',
  path: '/calls',
  getParentRoute: () => PortalRoute,
} as any)
const PortalCallbacksRoute = PortalCallbacksRouteImport.update({
  id: '/callbacks',
  path: '/callbacks',
  getParentRoute: () => PortalRoute,
} as any)
const PortalBillingRoute = PortalBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => PortalRoute,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/checkout/success',
  path: '/checkout/success',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWaTemplatesRoute = AdminWaTemplatesRouteImport.update({
  id: '/wa-templates',
  path: '/wa-templates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminScriptsRoute = AdminScriptsRouteImport.update({
  id: '/scripts',
  path: '/scripts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminResetPasswordRoute = AdminResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlansRoute = AdminPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNumbersRoute = AdminNumbersRouteImport.update({
  id: '/numbers',
  path: '/numbers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminForgotPasswordRoute = AdminForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCreditsRoute = AdminCreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientsRoute = AdminClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBillingRoute = AdminBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AdminRoute,
} as any)
const PortalWhatsappIndexRoute = PortalWhatsappIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalWhatsappRoute,
} as any)
const PortalCampaignsIndexRoute = PortalCampaignsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalCampaignsRoute,
} as any)
const PortalWhatsappTemplatesRoute = PortalWhatsappTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => PortalWhatsappRoute,
} as any)
const PortalWhatsappMessagesRoute = PortalWhatsappMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => PortalWhatsappRoute,
} as any)
const PortalWhatsappCampaignsRoute = PortalWhatsappCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => PortalWhatsappRoute,
} as any)
const PortalInboundReceptionistRoute =
  PortalInboundReceptionistRouteImport.update({
    id: '/receptionist',
    path: '/receptionist',
    getParentRoute: () => PortalInboundRoute,
  } as any)
const PortalInboundNumbersRoute = PortalInboundNumbersRouteImport.update({
  id: '/numbers',
  path: '/numbers',
  getParentRoute: () => PortalInboundRoute,
} as any)
const PortalInboundCallsRoute = PortalInboundCallsRouteImport.update({
  id: '/calls',
  path: '/calls',
  getParentRoute: () => PortalInboundRoute,
} as any)
const PortalInboundAnalyticsRoute = PortalInboundAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => PortalInboundRoute,
} as any)
const PortalCampaignsIdRoute = PortalCampaignsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PortalCampaignsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/credits': typeof AdminCreditsRoute
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/numbers': typeof AdminNumbersRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/admin/scripts': typeof AdminScriptsRoute
  '/admin/wa-templates': typeof AdminWaTemplatesRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/portal/billing': typeof PortalBillingRoute
  '/portal/callbacks': typeof PortalCallbacksRoute
  '/portal/calls': typeof PortalCallsRoute
  '/portal/campaigns': typeof PortalCampaignsRouteWithChildren
  '/portal/costs': typeof PortalCostsRoute
  '/portal/inbound': typeof PortalInboundRouteWithChildren
  '/portal/leads': typeof PortalLeadsRoute
  '/portal/live-calls': typeof PortalLiveCallsRoute
  '/portal/meetings': typeof PortalMeetingsRoute
  '/portal/scripts': typeof PortalScriptsRoute
  '/portal/settings': typeof PortalSettingsRoute
  '/portal/voice': typeof PortalVoiceRoute
  '/portal/whatsapp': typeof PortalWhatsappRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/portal/campaigns/$id': typeof PortalCampaignsIdRoute
  '/portal/inbound/analytics': typeof PortalInboundAnalyticsRoute
  '/portal/inbound/calls': typeof PortalInboundCallsRoute
  '/portal/inbound/numbers': typeof PortalInboundNumbersRoute
  '/portal/inbound/receptionist': typeof PortalInboundReceptionistRoute
  '/portal/whatsapp/campaigns': typeof PortalWhatsappCampaignsRoute
  '/portal/whatsapp/messages': typeof PortalWhatsappMessagesRoute
  '/portal/whatsapp/templates': typeof PortalWhatsappTemplatesRoute
  '/portal/campaigns/': typeof PortalCampaignsIndexRoute
  '/portal/whatsapp/': typeof PortalWhatsappIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/credits': typeof AdminCreditsRoute
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/numbers': typeof AdminNumbersRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/admin/scripts': typeof AdminScriptsRoute
  '/admin/wa-templates': typeof AdminWaTemplatesRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/portal/billing': typeof PortalBillingRoute
  '/portal/callbacks': typeof PortalCallbacksRoute
  '/portal/calls': typeof PortalCallsRoute
  '/portal/costs': typeof PortalCostsRoute
  '/portal/inbound': typeof PortalInboundRouteWithChildren
  '/portal/leads': typeof PortalLeadsRoute
  '/portal/live-calls': typeof PortalLiveCallsRoute
  '/portal/meetings': typeof PortalMeetingsRoute
  '/portal/scripts': typeof PortalScriptsRoute
  '/portal/settings': typeof PortalSettingsRoute
  '/portal/voice': typeof PortalVoiceRoute
  '/admin': typeof AdminIndexRoute
  '/portal': typeof PortalIndexRoute
  '/portal/campaigns/$id': typeof PortalCampaignsIdRoute
  '/portal/inbound/analytics': typeof PortalInboundAnalyticsRoute
  '/portal/inbound/calls': typeof PortalInboundCallsRoute
  '/portal/inbound/numbers': typeof PortalInboundNumbersRoute
  '/portal/inbound/receptionist': typeof PortalInboundReceptionistRoute
  '/portal/whatsapp/campaigns': typeof PortalWhatsappCampaignsRoute
  '/portal/whatsapp/messages': typeof PortalWhatsappMessagesRoute
  '/portal/whatsapp/templates': typeof PortalWhatsappTemplatesRoute
  '/portal/campaigns': typeof PortalCampaignsIndexRoute
  '/portal/whatsapp': typeof PortalWhatsappIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/credits': typeof AdminCreditsRoute
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/numbers': typeof AdminNumbersRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/admin/scripts': typeof AdminScriptsRoute
  '/admin/wa-templates': typeof AdminWaTemplatesRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/portal/billing': typeof PortalBillingRoute
  '/portal/callbacks': typeof PortalCallbacksRoute
  '/portal/calls': typeof PortalCallsRoute
  '/portal/campaigns': typeof PortalCampaignsRouteWithChildren
  '/portal/costs': typeof PortalCostsRoute
  '/portal/inbound': typeof PortalInboundRouteWithChildren
  '/portal/leads': typeof PortalLeadsRoute
  '/portal/live-calls': typeof PortalLiveCallsRoute
  '/portal/meetings': typeof PortalMeetingsRoute
  '/portal/scripts': typeof PortalScriptsRoute
  '/portal/settings': typeof PortalSettingsRoute
  '/portal/voice': typeof PortalVoiceRoute
  '/portal/whatsapp': typeof PortalWhatsappRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/portal/campaigns/$id': typeof PortalCampaignsIdRoute
  '/portal/inbound/analytics': typeof PortalInboundAnalyticsRoute
  '/portal/inbound/calls': typeof PortalInboundCallsRoute
  '/portal/inbound/numbers': typeof PortalInboundNumbersRoute
  '/portal/inbound/receptionist': typeof PortalInboundReceptionistRoute
  '/portal/whatsapp/campaigns': typeof PortalWhatsappCampaignsRoute
  '/portal/whatsapp/messages': typeof PortalWhatsappMessagesRoute
  '/portal/whatsapp/templates': typeof PortalWhatsappTemplatesRoute
  '/portal/campaigns/': typeof PortalCampaignsIndexRoute
  '/portal/whatsapp/': typeof PortalWhatsappIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/contact'
    | '/how-it-works'
    | '/login'
    | '/portal'
    | '/pricing'
    | '/register'
    | '/reset-password'
    | '/services'
    | '/admin/billing'
    | '/admin/clients'
    | '/admin/credits'
    | '/admin/forgot-password'
    | '/admin/login'
    | '/admin/numbers'
    | '/admin/plans'
    | '/admin/profile'
    | '/admin/reset-password'
    | '/admin/scripts'
    | '/admin/wa-templates'
    | '/checkout/success'
    | '/portal/billing'
    | '/portal/callbacks'
    | '/portal/calls'
    | '/portal/campaigns'
    | '/portal/costs'
    | '/portal/inbound'
    | '/portal/leads'
    | '/portal/live-calls'
    | '/portal/meetings'
    | '/portal/scripts'
    | '/portal/settings'
    | '/portal/voice'
    | '/portal/whatsapp'
    | '/admin/'
    | '/portal/'
    | '/portal/campaigns/$id'
    | '/portal/inbound/analytics'
    | '/portal/inbound/calls'
    | '/portal/inbound/numbers'
    | '/portal/inbound/receptionist'
    | '/portal/whatsapp/campaigns'
    | '/portal/whatsapp/messages'
    | '/portal/whatsapp/templates'
    | '/portal/campaigns/'
    | '/portal/whatsapp/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/how-it-works'
    | '/login'
    | '/pricing'
    | '/register'
    | '/reset-password'
    | '/services'
    | '/admin/billing'
    | '/admin/clients'
    | '/admin/credits'
    | '/admin/forgot-password'
    | '/admin/login'
    | '/admin/numbers'
    | '/admin/plans'
    | '/admin/profile'
    | '/admin/reset-password'
    | '/admin/scripts'
    | '/admin/wa-templates'
    | '/checkout/success'
    | '/portal/billing'
    | '/portal/callbacks'
    | '/portal/calls'
    | '/portal/costs'
    | '/portal/inbound'
    | '/portal/leads'
    | '/portal/live-calls'
    | '/portal/meetings'
    | '/portal/scripts'
    | '/portal/settings'
    | '/portal/voice'
    | '/admin'
    | '/portal'
    | '/portal/campaigns/$id'
    | '/portal/inbound/analytics'
    | '/portal/inbound/calls'
    | '/portal/inbound/numbers'
    | '/portal/inbound/receptionist'
    | '/portal/whatsapp/campaigns'
    | '/portal/whatsapp/messages'
    | '/portal/whatsapp/templates'
    | '/portal/campaigns'
    | '/portal/whatsapp'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/contact'
    | '/how-it-works'
    | '/login'
    | '/portal'
    | '/pricing'
    | '/register'
    | '/reset-password'
    | '/services'
    | '/admin/billing'
    | '/admin/clients'
    | '/admin/credits'
    | '/admin/forgot-password'
    | '/admin/login'
    | '/admin/numbers'
    | '/admin/plans'
    | '/admin/profile'
    | '/admin/reset-password'
    | '/admin/scripts'
    | '/admin/wa-templates'
    | '/checkout/success'
    | '/portal/billing'
    | '/portal/callbacks'
    | '/portal/calls'
    | '/portal/campaigns'
    | '/portal/costs'
    | '/portal/inbound'
    | '/portal/leads'
    | '/portal/live-calls'
    | '/portal/meetings'
    | '/portal/scripts'
    | '/portal/settings'
    | '/portal/voice'
    | '/portal/whatsapp'
    | '/admin/'
    | '/portal/'
    | '/portal/campaigns/$id'
    | '/portal/inbound/analytics'
    | '/portal/inbound/calls'
    | '/portal/inbound/numbers'
    | '/portal/inbound/receptionist'
    | '/portal/whatsapp/campaigns'
    | '/portal/whatsapp/messages'
    | '/portal/whatsapp/templates'
    | '/portal/campaigns/'
    | '/portal/whatsapp/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactRoute: typeof ContactRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LoginRoute: typeof LoginRoute
  PortalRoute: typeof PortalRouteWithChildren
  PricingRoute: typeof PricingRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ServicesRoute: typeof ServicesRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/portal/whatsapp': {
      id: '/portal/whatsapp'
      path: '/whatsapp'
      fullPath: '/portal/whatsapp'
      preLoaderRoute: typeof PortalWhatsappRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/voice': {
      id: '/portal/voice'
      path: '/voice'
      fullPath: '/portal/voice'
      preLoaderRoute: typeof PortalVoiceRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/settings': {
      id: '/portal/settings'
      path: '/settings'
      fullPath: '/portal/settings'
      preLoaderRoute: typeof PortalSettingsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/scripts': {
      id: '/portal/scripts'
      path: '/scripts'
      fullPath: '/portal/scripts'
      preLoaderRoute: typeof PortalScriptsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/meetings': {
      id: '/portal/meetings'
      path: '/meetings'
      fullPath: '/portal/meetings'
      preLoaderRoute: typeof PortalMeetingsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/live-calls': {
      id: '/portal/live-calls'
      path: '/live-calls'
      fullPath: '/portal/live-calls'
      preLoaderRoute: typeof PortalLiveCallsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/leads': {
      id: '/portal/leads'
      path: '/leads'
      fullPath: '/portal/leads'
      preLoaderRoute: typeof PortalLeadsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/inbound': {
      id: '/portal/inbound'
      path: '/inbound'
      fullPath: '/portal/inbound'
      preLoaderRoute: typeof PortalInboundRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/costs': {
      id: '/portal/costs'
      path: '/costs'
      fullPath: '/portal/costs'
      preLoaderRoute: typeof PortalCostsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/campaigns': {
      id: '/portal/campaigns'
      path: '/campaigns'
      fullPath: '/portal/campaigns'
      preLoaderRoute: typeof PortalCampaignsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/calls': {
      id: '/portal/calls'
      path: '/calls'
      fullPath: '/portal/calls'
      preLoaderRoute: typeof PortalCallsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/callbacks': {
      id: '/portal/callbacks'
      path: '/callbacks'
      fullPath: '/portal/callbacks'
      preLoaderRoute: typeof PortalCallbacksRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/billing': {
      id: '/portal/billing'
      path: '/billing'
      fullPath: '/portal/billing'
      preLoaderRoute: typeof PortalBillingRouteImport
      parentRoute: typeof PortalRoute
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/checkout/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/wa-templates': {
      id: '/admin/wa-templates'
      path: '/wa-templates'
      fullPath: '/admin/wa-templates'
      preLoaderRoute: typeof AdminWaTemplatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/scripts': {
      id: '/admin/scripts'
      path: '/scripts'
      fullPath: '/admin/scripts'
      preLoaderRoute: typeof AdminScriptsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reset-password': {
      id: '/admin/reset-password'
      path: '/reset-password'
      fullPath: '/admin/reset-password'
      preLoaderRoute: typeof AdminResetPasswordRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/plans': {
      id: '/admin/plans'
      path: '/plans'
      fullPath: '/admin/plans'
      preLoaderRoute: typeof AdminPlansRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/numbers': {
      id: '/admin/numbers'
      path: '/numbers'
      fullPath: '/admin/numbers'
      preLoaderRoute: typeof AdminNumbersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/forgot-password': {
      id: '/admin/forgot-password'
      path: '/forgot-password'
      fullPath: '/admin/forgot-password'
      preLoaderRoute: typeof AdminForgotPasswordRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/credits': {
      id: '/admin/credits'
      path: '/credits'
      fullPath: '/admin/credits'
      preLoaderRoute: typeof AdminCreditsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clients': {
      id: '/admin/clients'
      path: '/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AdminClientsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/billing': {
      id: '/admin/billing'
      path: '/billing'
      fullPath: '/admin/billing'
      preLoaderRoute: typeof AdminBillingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/portal/whatsapp/': {
      id: '/portal/whatsapp/'
      path: '/'
      fullPath: '/portal/whatsapp/'
      preLoaderRoute: typeof PortalWhatsappIndexRouteImport
      parentRoute: typeof PortalWhatsappRoute
    }
    '/portal/campaigns/': {
      id: '/portal/campaigns/'
      path: '/'
      fullPath: '/portal/campaigns/'
      preLoaderRoute: typeof PortalCampaignsIndexRouteImport
      parentRoute: typeof PortalCampaignsRoute
    }
    '/portal/whatsapp/templates': {
      id: '/portal/whatsapp/templates'
      path: '/templates'
      fullPath: '/portal/whatsapp/templates'
      preLoaderRoute: typeof PortalWhatsappTemplatesRouteImport
      parentRoute: typeof PortalWhatsappRoute
    }
    '/portal/whatsapp/messages': {
      id: '/portal/whatsapp/messages'
      path: '/messages'
      fullPath: '/portal/whatsapp/messages'
      preLoaderRoute: typeof PortalWhatsappMessagesRouteImport
      parentRoute: typeof PortalWhatsappRoute
    }
    '/portal/whatsapp/campaigns': {
      id: '/portal/whatsapp/campaigns'
      path: '/campaigns'
      fullPath: '/portal/whatsapp/campaigns'
      preLoaderRoute: typeof PortalWhatsappCampaignsRouteImport
      parentRoute: typeof PortalWhatsappRoute
    }
    '/portal/inbound/receptionist': {
      id: '/portal/inbound/receptionist'
      path: '/receptionist'
      fullPath: '/portal/inbound/receptionist'
      preLoaderRoute: typeof PortalInboundReceptionistRouteImport
      parentRoute: typeof PortalInboundRoute
    }
    '/portal/inbound/numbers': {
      id: '/portal/inbound/numbers'
      path: '/numbers'
      fullPath: '/portal/inbound/numbers'
      preLoaderRoute: typeof PortalInboundNumbersRouteImport
      parentRoute: typeof PortalInboundRoute
    }
    '/portal/inbound/calls': {
      id: '/portal/inbound/calls'
      path: '/calls'
      fullPath: '/portal/inbound/calls'
      preLoaderRoute: typeof PortalInboundCallsRouteImport
      parentRoute: typeof PortalInboundRoute
    }
    '/portal/inbound/analytics': {
      id: '/portal/inbound/analytics'
      path: '/analytics'
      fullPath: '/portal/inbound/analytics'
      preLoaderRoute: typeof PortalInboundAnalyticsRouteImport
      parentRoute: typeof PortalInboundRoute
    }
    '/portal/campaigns/$id': {
      id: '/portal/campaigns/$id'
      path: '/$id'
      fullPath: '/portal/campaigns/$id'
      preLoaderRoute: typeof PortalCampaignsIdRouteImport
      parentRoute: typeof PortalCampaignsRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBillingRoute: typeof AdminBillingRoute
  AdminClientsRoute: typeof AdminClientsRoute
  AdminCreditsRoute: typeof AdminCreditsRoute
  AdminForgotPasswordRoute: typeof AdminForgotPasswordRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminNumbersRoute: typeof AdminNumbersRoute
  AdminPlansRoute: typeof AdminPlansRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminResetPasswordRoute: typeof AdminResetPasswordRoute
  AdminScriptsRoute: typeof AdminScriptsRoute
  AdminWaTemplatesRoute: typeof AdminWaTemplatesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBillingRoute: AdminBillingRoute,
  AdminClientsRoute: AdminClientsRoute,
  AdminCreditsRoute: AdminCreditsRoute,
  AdminForgotPasswordRoute: AdminForgotPasswordRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminNumbersRoute: AdminNumbersRoute,
  AdminPlansRoute: AdminPlansRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminResetPasswordRoute: AdminResetPasswordRoute,
  AdminScriptsRoute: AdminScriptsRoute,
  AdminWaTemplatesRoute: AdminWaTemplatesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PortalCampaignsRouteChildren {
  PortalCampaignsIdRoute: typeof PortalCampaignsIdRoute
  PortalCampaignsIndexRoute: typeof PortalCampaignsIndexRoute
}

const PortalCampaignsRouteChildren: PortalCampaignsRouteChildren = {
  PortalCampaignsIdRoute: PortalCampaignsIdRoute,
  PortalCampaignsIndexRoute: PortalCampaignsIndexRoute,
}

const PortalCampaignsRouteWithChildren = PortalCampaignsRoute._addFileChildren(
  PortalCampaignsRouteChildren,
)

interface PortalInboundRouteChildren {
  PortalInboundAnalyticsRoute: typeof PortalInboundAnalyticsRoute
  PortalInboundCallsRoute: typeof PortalInboundCallsRoute
  PortalInboundNumbersRoute: typeof PortalInboundNumbersRoute
  PortalInboundReceptionistRoute: typeof PortalInboundReceptionistRoute
}

const PortalInboundRouteChildren: PortalInboundRouteChildren = {
  PortalInboundAnalyticsRoute: PortalInboundAnalyticsRoute,
  PortalInboundCallsRoute: PortalInboundCallsRoute,
  PortalInboundNumbersRoute: PortalInboundNumbersRoute,
  PortalInboundReceptionistRoute: PortalInboundReceptionistRoute,
}

const PortalInboundRouteWithChildren = PortalInboundRoute._addFileChildren(
  PortalInboundRouteChildren,
)

interface PortalWhatsappRouteChildren {
  PortalWhatsappCampaignsRoute: typeof PortalWhatsappCampaignsRoute
  PortalWhatsappMessagesRoute: typeof PortalWhatsappMessagesRoute
  PortalWhatsappTemplatesRoute: typeof PortalWhatsappTemplatesRoute
  PortalWhatsappIndexRoute: typeof PortalWhatsappIndexRoute
}

const PortalWhatsappRouteChildren: PortalWhatsappRouteChildren = {
  PortalWhatsappCampaignsRoute: PortalWhatsappCampaignsRoute,
  PortalWhatsappMessagesRoute: PortalWhatsappMessagesRoute,
  PortalWhatsappTemplatesRoute: PortalWhatsappTemplatesRoute,
  PortalWhatsappIndexRoute: PortalWhatsappIndexRoute,
}

const PortalWhatsappRouteWithChildren = PortalWhatsappRoute._addFileChildren(
  PortalWhatsappRouteChildren,
)

interface PortalRouteChildren {
  PortalBillingRoute: typeof PortalBillingRoute
  PortalCallbacksRoute: typeof PortalCallbacksRoute
  PortalCallsRoute: typeof PortalCallsRoute
  PortalCampaignsRoute: typeof PortalCampaignsRouteWithChildren
  PortalCostsRoute: typeof PortalCostsRoute
  PortalInboundRoute: typeof PortalInboundRouteWithChildren
  PortalLeadsRoute: typeof PortalLeadsRoute
  PortalLiveCallsRoute: typeof PortalLiveCallsRoute
  PortalMeetingsRoute: typeof PortalMeetingsRoute
  PortalScriptsRoute: typeof PortalScriptsRoute
  PortalSettingsRoute: typeof PortalSettingsRoute
  PortalVoiceRoute: typeof PortalVoiceRoute
  PortalWhatsappRoute: typeof PortalWhatsappRouteWithChildren
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalBillingRoute: PortalBillingRoute,
  PortalCallbacksRoute: PortalCallbacksRoute,
  PortalCallsRoute: PortalCallsRoute,
  PortalCampaignsRoute: PortalCampaignsRouteWithChildren,
  PortalCostsRoute: PortalCostsRoute,
  PortalInboundRoute: PortalInboundRouteWithChildren,
  PortalLeadsRoute: PortalLeadsRoute,
  PortalLiveCallsRoute: PortalLiveCallsRoute,
  PortalMeetingsRoute: PortalMeetingsRoute,
  PortalScriptsRoute: PortalScriptsRoute,
  PortalSettingsRoute: PortalSettingsRoute,
  PortalVoiceRoute: PortalVoiceRoute,
  PortalWhatsappRoute: PortalWhatsappRouteWithChildren,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactRoute: ContactRoute,
  HowItWorksRoute: HowItWorksRoute,
  LoginRoute: LoginRoute,
  PortalRoute: PortalRouteWithChildren,
  PricingRoute: PricingRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ServicesRoute: ServicesRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
